services:
  backend:
    build:
      context: ./breezy-backend
      dockerfile: Dockerfile
    container_name: breezy-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongo:27017/breezy   # 👈 clé du succès
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - breezy-net


  frontend:
    build:
      context: ./breezy-frontend
      dockerfile: Dockerfile
    container_name: breezy-frontend
    environment:
      - NODE_ENV = production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - breezy-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27019:27017"            # 27019 côté host, 27017 côté réseau Docker
    volumes:
      - mongo-data:/data/db
    networks:
      - breezy-net





      


volumes:
  mongo-data:

networks:
  breezy-net: