services:
  frontend:
    build:
      context: ./breezy-frontend
      dockerfile: Dockerfile
    container_name: breezy-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - breezy-net

  backend:
    build:
      context: ./breezy-backend
      dockerfile: Dockerfile
    container_name: breezy-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/project
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - breezy-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - breezy-net

volumes:
  mongo-data:

networks:
  breezy-net: