services:
  frontend:
    build:
      context: ./breezy-frontend
      dockerfile: Dockerfile
    container_name: breezy-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL= ${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - backend
    networks:
      - breezy-net

  backend:
    build:
      context: ./breezy-backend
      dockerfile: Dockerfile
    container_name: breezy-backend
    ports:
      - "5000:5000"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongo:27017/breezy
      - PORT=5000
      - JWT_SECRET= ${JWT_SECRET}
      - SMTP_HOST= ${SMTP_HOST}
      - SMTP_PORT= ${SMTP_PORT}
      - SMTP_USER= ${SMTP_USER}
      - SMTP_PASS= ${SMTP_PASS}
      - NODE_ENV = production
    depends_on:
      - mongo
    networks:
      - breezy-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - breezy-net




      


volumes:
  mongo-data:

networks:
  breezy-net: